### ISSUE TITLE
Deprecated "rnpm"

### ISSUE THREAD

**Issue by sorinalinpavel** [fqborges/react-native-maps#13]
**warn** The following packages use deprecated "rnpm" config that will stop working from next release:
  - react-native-maps-osmdroid: https://npmjs.com/package/react-native-maps-osmdroid
Please notify their maintainers about it. You can find more details at https://github.com/react-native-community/cli/blob/master/docs/configuration.md#migration-guide.

This happens with your npm version.

You need to update this because it will stop all the users from building on android.

**Comment by tanoabeleyra** [comment]
Any progress on this?

**Comment by sorinalinpavel** [comment]
You can use their GitHub version until they will actually update the NPM version as well.
In order to do that, in your package.json file, instead of the version you can put git+ git URL.

The final results should look like this:

"react-native-maps": "git+https://github.com/fqborges/react-native-maps-osmdroid.git"

Let me know if this is fixing your issue.

**Comment by tanoabeleyra** [comment]
@sorinalinpavel Thanks, I made my own fork, merged master of https://github.com/react-native-community/react-native-maps and it's working.

**Comment by sorinalinpavel** [comment]
Happy to hear that it worked.

I will leave this issue here because it might help others and well.

**Comment by fqborges** [comment]
I am upgrading this lib by merging the last version of react-native-maps.

There will be still a small issue regarding androidx, support lib and jetifier, but I am confident this issue will be fixed.

**Comment by fqborges** [comment]
Fixed on the last update.
