### ISSUE TITLE
Typescript import error - not a module

### ISSUE THREAD

**Issue by xeruf** [fqborges/react-native-maps#14]
I installed the latest version 0.23.0-rc4, but the following import:
```
import MapView, { Marker } from 'react-native-maps-osmdroid'
```
leads to this error
```
TS2306: File '/home/janek/daten/projects/apps/btl-app/node_modules/react-native-maps-osmdroid/index.d.ts' is not a module.
```

Using Expo SDK 36.0.1 and React 16.9.0

**Comment by johannamelly** [comment]
Hi, I had the same issue. You can follow these steps:
1. create a "types" folder at the root of your project
2. in your "tsconfig.json" file, add
```
"typeRoots": [
      "./types",
    ]
```
3. in your "types" folder, create a "react-native-maps-osmdroid" folder
4. copy and paste the "index.d.ts" file that you find in node_modules/react-native-maps-osmdroid/ into your newly created "react-native-maps-osmdroid" folder
5. change the first line of the "index.d.ts" (the one you just pasted) from `declare module "react-native-maps" {` to `declare module "react-native-maps-osmdroid" {`

It should work! :)

**Comment by fqborges** [comment]
Fixed for the next release. I am upgrading this lib by merging the last version of react-native-maps.

**Comment by fqborges** [comment]
Fixed
